### PR TITLE
Fix spelling errors README.txt

### PR DESCRIPTION
**Pull request by AranVink**

### CODE REVIEW

**Comment by volkertb** [comment]
LGTM. Thanks!

**Comment by volkertb** [comment]
@AranVink Thanks! One small request: Can you maybe `commit --amend` your commit and prefix your commit message with `docs: `, so that it conforms to the [Conventional Commits](https://www.conventionalcommits.org) convention? I know we haven't consistently done that until now, but with a [recent merge](https://github.com/crazii/SBEMU/pull/82), every release will  now have release notes generated, and each commits will be auto-categorized under sublists if we use these prefixes properly.

Thanks for understanding!

Other than that, LGTM. :slightly_smiling_face:

**Comment by AranVink** [comment]
Amended 🚀
Just a thought: would it be something to add this convention to a `CONTRIBUTING` file?

**Comment by volkertb** [comment]
@AranVink Thanks! And good suggestion about adding a `CONTRIBUTING` file. I'll look into adding one.

**Pull request merged**
