### PR TITLE
Revert "Test SBEMU.EXE by running it in a DOS VM in GitHub Actions on any commit to a Pull Request"

### PR DESCRIPTION
**Pull request by volkertb**
Reverts crazii/SBEMU#76

### CODE REVIEW

**Comment by volkertb** [comment]
@crazii OK, let's try reverting this merge, to see if this was indeed the cause of the release breakage.

**Comment by crazii** [comment]
OK, sorry that I should confirm before merging.

**Comment by volkertb** [comment]
@crazii No, that's good. It's always good to have reviewers. Thanks. :slightly_smiling_face:

Now, let's see if this resolves the release breakage. If it does, I'll dig into this deeper. :crossed_fingers:

**Comment by crazii** [comment]
There's still some errors, :)

**Pull request merged**
