### PR TITLE
Fix build on case-sensitive filesystems, add makefile

### PR DESCRIPTION
**Pull request by thp**
This makes it possible to easily cross-build on Linux, while the DOS build should be unaffected.

### CODE REVIEW

**Comment by volkertb** [comment]
@thp It would be great if we could figure out why the Makefile that GPR2MAK generates from sbemu.gpr does not work, and fix that. That way, `sbemu.gpr`, the RHIDE project file, would still remain the "single source of truth" in terms of how to build the project, instead of having to maintain both the GPR file and the separate Makefile, going forward.

I know that @crazii prefers to develop this project in RHIDE in DOS.

**Comment by thp** [comment]
> @thp It would be great if we could figure out why the Makefile that GPR2MAK generates from sbemu.gpr does not work, and fix that. That way, `sbemu.gpr`, the RHIDE project file, would still remain the "single source of truth" in terms of how to build the project, instead of having to maintain both the GPR file and the separate Makefile, going forward.

Not sure where I would find GPR2MAK. I definitely don't see it on my DJGPP installations on macOS and Linux. In any case, the file renames and include directive fixes would be needed. I can split off the `makefile` from this PR if @crazii doesn't want to merge it as-is.

For me, the important thing was that I can clone and build the project easily on a Linux machine with DJGPP without having to download additional tools or emulators.

**Comment by volkertb** [comment]
`GPR2MAK.EXE` comes with [RHIDE](https://sourceforge.net/projects/rhide/), the open-source DOS-based C/C++ IDE that @crazii used to develop this project.

I have the same goal as you do, namely being able to build the project in Linux without affecting the ability to build it in DOS. I also figured out a working Makefile, but like you, I had to add it to the project, and since I expect @crazii to continue developing the project with RHIDE (assuming that he picks up development again), we would have the risk of the Makefile and the `sbemu.gpr` file diverging. Keeping one of those files as the single source of truth, and having the other one dynamically generated from it, would be much preferable for long-term maintainability.

That's what `GPR2MAK` is supposed to do. However, I could not get it to generate a correct Makefile. However, @4nd3r50ncr [apparently managed to figure that out](https://github.com/crazii/SBEMU/issues/31).

**Comment by thp** [comment]
> `GPR2MAK.EXE` comes with [RHIDE](https://sourceforge.net/projects/rhide/), the open-source DOS-based C/C++ IDE that @crazii used to develop this project.

Yeah I don't want to install DOSBox to work on this project.

> [I also figured out a working Makefile](https://github.com/crazii/SBEMU/issues/19#issuecomment-1571077137)

That's a shell script as far as I can tell. `make` has some other features like allowing parallel builds and rebuilding only what has changed.

Using `GPR2MAK` would defeat the purpose of making it as easy as running `git clone ... ; make` to build the project.

**Comment by crazii** [comment]
> > `GPR2MAK.EXE` comes with [RHIDE](https://sourceforge.net/projects/rhide/), the open-source DOS-based C/C++ IDE that @crazii used to develop this project.
> 
> Yeah I don't want to install DOSBox to work on this project.
> 
> > [I also figured out a working Makefile](https://github.com/crazii/SBEMU/issues/19#issuecomment-1571077137)
> 
> That's a shell script as far as I can tell. `make` has some other features like allowing parallel builds and rebuilding only what has changed.
> 
> Using `GPR2MAK` would defeat the purpose of making it as easy as running `git clone ... ; make` to build the project.

Yes, I just use the RHIDE for some kind of "retro coding" and build & run on the fly, It should have makefile.

**Comment by volkertb** [comment]
OK. Then there a consensus for adding a separate Makefile, instead of having one generated from the GPR file.

I'll update [my PR](https://github.com/crazii/SBEMU/pull/21) once this one is merged, since I can greatly simplify things in the CI/CD configuration if I don't have to work around the incompatibility of the project with case-sensitive file systems. Thanks.

**Pull request merged**
